# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  pull_request:
    branches:
      - master
      - dev
  push:
    branches: [ master ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
        
    - name: Install deps
      run: |
        python -m pip install --upgrade pip setuptools wheel
        echo "*************** Path during install deps ***************"
        echo $PWD
        
    - name: install caiman
      run: |
        cd ..
        git clone https://github.com/flatironinstitute/CaImAn.git
        cd CaImAn
        pip install -r requirements.txt
        pip install .
        caimanmanager.py install
        echo "*************** Path during install caiman ***************"
        echo $PWD
        
    - name: Install mesmerize-core
      run: |
        echo "*************** Path during install mesmerize ***************"
        echo $PWD
        pip install -r requirements.txt
        pip install git+https://github.com/pandas-dev/pandas.git
        pip install pytest
        pip install .        
        
    - name: Test with pytest
      run: |
        DOWNLOAD_GROUND_TRUTHS=1 pytest -s .

